#ifndef VERSION_HPP
#define VERSION_HPP

#define OPENMW_VERSION_MAJOR 0
#define OPENMW_VERSION_MINOR 31
#define OPENMW_VERSION_RELEASE 0
#define OPENMW_VERSION "0.31.0"

#define OPENMW_VERSION_COMMITHASH ""
#define OPENMW_VERSION_TAGHASH ""

#endif // VERSION_HPP

